name: Deploy Infraestrutura
run-name: ${{ github.actor }} iniciou o deploy 

on:
  push:
    branches: [ "stg", "prod" ]
  workflow_dispatch:

permissions:
  id-token: write # permite que a action solicite o token OIDC
  contents: read  # permite que a action baixe o seu código

jobs:
  # 1. Validação do código
  codevalidate:
    name: "Verifica o código Terraform"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init -backend=false
      - run: terraform validate

  # 2. Verificação de Segurança
  security_scan:
    name: "Análise de Segurança"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
          
  # 3. Provisionamento e Configuração
  infraestrutura:
    name: "Provisionar e Configurar"
    runs-on: ubuntu-latest
    needs: [codevalidate, security_scan]
    env:
      TF_VAR_bloco_ips_liberados: ${{ secrets.IPS_PERMITIDOS }}
      TF_WORKING_DIR: ${{ github.ref == 'refs/heads/prod' && './production' || './staging' }}
      TF_VAR_chave_ssh: ${{ github.ref == 'refs/heads/production' && secrets.CHAVE_PROD || secrets.CHAVE_STAG }}
      TF_VAR_ssm_instance_profile_name: ${{ secrets.SSM_PROFILE_NAME }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Criar arquivo de backend (PROD)
        if: github.ref == 'refs/heads/prod' 
        run: |
          cat <<'EOF' > backend-config.tfvars
          ${{ secrets.BACKEND_CONFIG_PROD }}
          EOF

      - name: Criar arquivo de backend (STG)
        if: github.ref == 'refs/heads/stg' 
        run: |
          cat <<'EOF' > backend-config.tfvars
          ${{ secrets.BACKEND_CONFIG_STG }}
          EOF

      - name: Terraform Init
        run: terraform init -backend-config=../backend-config.tfvars -reconfigure
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Instalar Session Manager Plugin
        run: |
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          sudo dpkg -i session-manager-plugin.deb

      - name: Instalar Dependências AWS para Ansible
        run: |
          ansible-galaxy collection install amazon.aws
          pipx inject ansible-core boto3 botocore

      - name: Configurar Inventário do Ansible (Usando IDs)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          echo "[web]" > hosts.ini
          echo "$(terraform output -raw instance_id_web)" >> hosts.ini
          echo "" >> hosts.ini
          echo "[db]" >> hosts.ini
          echo "$(terraform output -raw instance_id_db)" >> hosts.ini

          echo "--- Conteúdo do hosts.ini ---"
          cat hosts.ini
          echo "A região detectada é: ${{ secrets.AWS_DEFAULT_REGION }}"

      - name: Rodar Ansible Playbook via SSM
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          # Aguarda o agente SSM estabilizar na instância
          sleep 30
          ansible-playbook -i hosts.ini ../playbook.yml \
            --connection aws_ssm \
            -e "ansible_aws_ssm_region=${{ secrets.AWS_DEFAULT_REGION }}" \
            -e "ansible_python_interpreter=/usr/bin/python3"